export const FETCH_DISHES = "FETCH_DISHES";
export const ADD_DISH = "ADD_DISH";
export const PUBLIC_DISHES_DATA_RECEIVED = "PUBLIC_DISHES_DATA_RECEIVED";
export const PRIVATE_DISHES_DATA_RECEIVED = "PRIVATE_DISHES_DATA_RECEIVED";
export const FETCH_PUBLIC_DISHES = "FETCH_PUBLIC_DISHES";
