// Dishes
export const FETCH_DISHES = "FETCH_DISHES";
export const ADD_DISH = "ADD_DISH";
export const PUBLIC_DISHES_DATA_RECEIVED = "PUBLIC_DISHES_DATA_RECEIVED";
export const PRIVATE_DISHES_DATA_RECEIVED = "PRIVATE_DISHES_DATA_RECEIVED";
export const FETCH_PUBLIC_DISHES = "FETCH_PUBLIC_DISHES";

// Meals
export const FETCH_MEALS = "FETCH_MEALS";
export const FETCH_MEALS_DATA_RECIEVED = "FETCH_MEALS_DATA_RECIEVED";

// Menus
export const FETCH_PRIVATE_MENUS = "FETCH_PRIVATE_MENUS";
export const FETCH_PUBLIC_MENUS = "FETCH_PUBLIC_MENUS";
export const PRIVATE_MENUS_DATA_RECIEVED = "PRIVATE_MENUS_DATA_RECIEVED";
export const PUBLIC_MENUS_DATA_RECIEVED = "PUBLIC_MENUS_DATA_RECIEVED";
export const SET_MENU = "SET_MENU";
